export default [
	{
		id: 1,
		header: "표지",
		type: "표지",
		status: "진행 중",
		target: "18",
		limit: "5",
		reviewer: "Eddie Lake",
	},
	{
		id: 2,
		header: "목차",
		type: "목차",
		status: "완료",
		target: "29",
		limit: "24",
		reviewer: "Eddie Lake",
	},
	{
		id: 3,
		header: "요약",
		type: "설명",
		status: "완료",
		target: "10",
		limit: "13",
		reviewer: "Eddie Lake",
	},
	{
		id: 4,
		header: "기술 접근법",
		type: "설명",
		status: "완료",
		target: "27",
		limit: "23",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 5,
		header: "디자인",
		type: "설명",
		status: "진행 중",
		target: "2",
		limit: "16",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 6,
		header: "기능",
		type: "설명",
		status: "진행 중",
		target: "20",
		limit: "8",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 7,
		header: "기존 시스템과의 통합",
		type: "설명",
		status: "진행 중",
		target: "19",
		limit: "21",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 8,
		header: "혁신과 장점",
		type: "설명",
		status: "완료",
		target: "25",
		limit: "26",
		reviewer: "검토자 지정",
	},
	{
		id: 9,
		header: "EMR의 혁신적 솔루션 개요",
		type: "기술 콘텐츠",
		status: "완료",
		target: "7",
		limit: "23",
		reviewer: "검토자 지정",
	},
	{
		id: 10,
		header: "고급 알고리즘 및 머신러닝",
		type: "설명",
		status: "완료",
		target: "30",
		limit: "28",
		reviewer: "검토자 지정",
	},
	{
		id: 11,
		header: "적응형 통신 프로토콜",
		type: "설명",
		status: "완료",
		target: "9",
		limit: "31",
		reviewer: "검토자 지정",
	},
	{
		id: 12,
		header: "현재 기술 대비 장점",
		type: "설명",
		status: "완료",
		target: "12",
		limit: "0",
		reviewer: "검토자 지정",
	},
	{
		id: 13,
		header: "과거 성과",
		type: "설명",
		status: "완료",
		target: "22",
		limit: "33",
		reviewer: "검토자 지정",
	},
	{
		id: 14,
		header: "고객 피드백 및 만족도",
		type: "설명",
		status: "완료",
		target: "15",
		limit: "34",
		reviewer: "검토자 지정",
	},
	{
		id: 15,
		header: "구현 과제 및 솔루션",
		type: "설명",
		status: "완료",
		target: "3",
		limit: "35",
		reviewer: "검토자 지정",
	},
	{
		id: 16,
		header: "보안 조치 및 데이터 보호 정책",
		type: "설명",
		status: "진행 중",
		target: "6",
		limit: "36",
		reviewer: "검토자 지정",
	},
	{
		id: 17,
		header: "확장성 및 미래 대비",
		type: "설명",
		status: "완료",
		target: "4",
		limit: "37",
		reviewer: "검토자 지정",
	},
	{
		id: 18,
		header: "비용 편익 분석",
		type: "일반 언어",
		status: "완료",
		target: "14",
		limit: "38",
		reviewer: "검토자 지정",
	},
	{
		id: 19,
		header: "사용자 교육 및 온보딩 경험",
		type: "설명",
		status: "완료",
		target: "17",
		limit: "39",
		reviewer: "검토자 지정",
	},
	{
		id: 20,
		header: "향후 개발 로드맵",
		type: "설명",
		status: "완료",
		target: "11",
		limit: "40",
		reviewer: "검토자 지정",
	},
	{
		id: 21,
		header: "시스템 아키텍처 개요",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "24",
		limit: "18",
		reviewer: "Maya Johnson",
	},
	{
		id: 22,
		header: "위험 관리 계획",
		type: "설명",
		status: "완료",
		target: "15",
		limit: "22",
		reviewer: "Carlos Rodriguez",
	},
	{
		id: 23,
		header: "규정 준수 문서",
		type: "법률",
		status: "진행 중",
		target: "31",
		limit: "27",
		reviewer: "Sarah Chen",
	},
	{
		id: 24,
		header: "API 문서",
		type: "기술 콘텐츠",
		status: "완료",
		target: "8",
		limit: "12",
		reviewer: "Raj Patel",
	},
	{
		id: 25,
		header: "사용자 인터페이스 목업",
		type: "비주얼",
		status: "진행 중",
		target: "19",
		limit: "25",
		reviewer: "Leila Ahmadi",
	},
	{
		id: 26,
		header: "데이터베이스 스키마",
		type: "기술 콘텐츠",
		status: "완료",
		target: "22",
		limit: "20",
		reviewer: "Thomas Wilson",
	},
	{
		id: 27,
		header: "테스트 방법론",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "17",
		limit: "14",
		reviewer: "검토자 지정",
	},
	{
		id: 28,
		header: "배포 전략",
		type: "설명",
		status: "완료",
		target: "26",
		limit: "30",
		reviewer: "Eddie Lake",
	},
	{
		id: 29,
		header: "예산 분석",
		type: "재무",
		status: "진행 중",
		target: "13",
		limit: "16",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 30,
		header: "시장 분석",
		type: "리서치",
		status: "완료",
		target: "29",
		limit: "32",
		reviewer: "Sophia Martinez",
	},
	{
		id: 31,
		header: "경쟁사 비교",
		type: "리서치",
		status: "진행 중",
		target: "21",
		limit: "19",
		reviewer: "검토자 지정",
	},
	{
		id: 32,
		header: "유지보수 계획",
		type: "기술 콘텐츠",
		status: "완료",
		target: "16",
		limit: "23",
		reviewer: "Alex Thompson",
	},
	{
		id: 33,
		header: "사용자 페르소나",
		type: "리서치",
		status: "진행 중",
		target: "27",
		limit: "24",
		reviewer: "Nina Patel",
	},
	{
		id: 34,
		header: "접근성 준수",
		type: "법률",
		status: "완료",
		target: "18",
		limit: "21",
		reviewer: "검토자 지정",
	},
	{
		id: 35,
		header: "성능 지표",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "23",
		limit: "26",
		reviewer: "David Kim",
	},
	{
		id: 36,
		header: "재해 복구 계획",
		type: "기술 콘텐츠",
		status: "완료",
		target: "14",
		limit: "17",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 37,
		header: "서드파티 통합",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "25",
		limit: "28",
		reviewer: "Eddie Lake",
	},
	{
		id: 38,
		header: "사용자 피드백 요약",
		type: "리서치",
		status: "완료",
		target: "20",
		limit: "15",
		reviewer: "검토자 지정",
	},
	{
		id: 39,
		header: "현지화 전략",
		type: "설명",
		status: "진행 중",
		target: "12",
		limit: "19",
		reviewer: "Maria Garcia",
	},
	{
		id: 40,
		header: "모바일 호환성",
		type: "기술 콘텐츠",
		status: "완료",
		target: "28",
		limit: "31",
		reviewer: "James Wilson",
	},
	{
		id: 41,
		header: "데이터 마이그레이션 계획",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "19",
		limit: "22",
		reviewer: "검토자 지정",
	},
	{
		id: 42,
		header: "품질 보증 프로토콜",
		type: "기술 콘텐츠",
		status: "완료",
		target: "30",
		limit: "33",
		reviewer: "Priya Singh",
	},
	{
		id: 43,
		header: "이해관계자 분석",
		type: "리서치",
		status: "진행 중",
		target: "11",
		limit: "14",
		reviewer: "Eddie Lake",
	},
	{
		id: 44,
		header: "환경 영향 평가",
		type: "리서치",
		status: "완료",
		target: "24",
		limit: "27",
		reviewer: "검토자 지정",
	},
	{
		id: 45,
		header: "지식재산권",
		type: "법률",
		status: "진행 중",
		target: "17",
		limit: "20",
		reviewer: "Sarah Johnson",
	},
	{
		id: 46,
		header: "고객 지원 프레임워크",
		type: "설명",
		status: "완료",
		target: "22",
		limit: "25",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 47,
		header: "버전 관리 전략",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "15",
		limit: "18",
		reviewer: "검토자 지정",
	},
	{
		id: 48,
		header: "지속적 통합 파이프라인",
		type: "기술 콘텐츠",
		status: "완료",
		target: "26",
		limit: "29",
		reviewer: "Michael Chen",
	},
	{
		id: 49,
		header: "규제 준수",
		type: "법률",
		status: "진행 중",
		target: "13",
		limit: "16",
		reviewer: "검토자 지정",
	},
	{
		id: 50,
		header: "사용자 인증 시스템",
		type: "기술 콘텐츠",
		status: "완료",
		target: "28",
		limit: "31",
		reviewer: "Eddie Lake",
	},
	{
		id: 51,
		header: "데이터 분석 프레임워크",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "21",
		limit: "24",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 52,
		header: "클라우드 인프라",
		type: "기술 콘텐츠",
		status: "완료",
		target: "16",
		limit: "19",
		reviewer: "검토자 지정",
	},
	{
		id: 53,
		header: "네트워크 보안 조치",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "29",
		limit: "32",
		reviewer: "Lisa Wong",
	},
	{
		id: 54,
		header: "프로젝트 타임라인",
		type: "계획",
		status: "완료",
		target: "14",
		limit: "17",
		reviewer: "Eddie Lake",
	},
	{
		id: 55,
		header: "리소스 할당",
		type: "계획",
		status: "진행 중",
		target: "27",
		limit: "30",
		reviewer: "검토자 지정",
	},
	{
		id: 56,
		header: "팀 구조 및 역할",
		type: "계획",
		status: "완료",
		target: "20",
		limit: "23",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 57,
		header: "커뮤니케이션 프로토콜",
		type: "계획",
		status: "진행 중",
		target: "15",
		limit: "18",
		reviewer: "검토자 지정",
	},
	{
		id: 58,
		header: "성공 지표",
		type: "계획",
		status: "완료",
		target: "30",
		limit: "33",
		reviewer: "Eddie Lake",
	},
	{
		id: 59,
		header: "국제화 지원",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "23",
		limit: "26",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 60,
		header: "백업 및 복구 절차",
		type: "기술 콘텐츠",
		status: "완료",
		target: "18",
		limit: "21",
		reviewer: "검토자 지정",
	},
	{
		id: 61,
		header: "모니터링 및 알림 시스템",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "25",
		limit: "28",
		reviewer: "Daniel Park",
	},
	{
		id: 62,
		header: "코드 리뷰 가이드라인",
		type: "기술 콘텐츠",
		status: "완료",
		target: "12",
		limit: "15",
		reviewer: "Eddie Lake",
	},
	{
		id: 63,
		header: "문서화 표준",
		type: "기술 콘텐츠",
		status: "진행 중",
		target: "27",
		limit: "30",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 64,
		header: "릴리스 관리 프로세스",
		type: "계획",
		status: "완료",
		target: "22",
		limit: "25",
		reviewer: "검토자 지정",
	},
	{
		id: 65,
		header: "기능 우선순위 매트릭스",
		type: "계획",
		status: "진행 중",
		target: "19",
		limit: "22",
		reviewer: "Emma Davis",
	},
	{
		id: 66,
		header: "기술 부채 평가",
		type: "기술 콘텐츠",
		status: "완료",
		target: "24",
		limit: "27",
		reviewer: "Eddie Lake",
	},
	{
		id: 67,
		header: "용량 계획",
		type: "계획",
		status: "진행 중",
		target: "21",
		limit: "24",
		reviewer: "Jamik Tashpulatov",
	},
	{
		id: 68,
		header: "서비스 수준 계약",
		type: "법률",
		status: "완료",
		target: "26",
		limit: "29",
		reviewer: "검토자 지정",
	},
];
